#!/bin/bash

set -e

if [ ! -d /var/lib/mysql/mysql ]; then
    mysql_install_db
fi

cat > /tmp/init.sql <<EOF
CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER IF NOT EXISTS '$WORDPRESS_DB_USER'@'%' IDENTIFIED BY '$WORDPRESS_DB_PASSWORD';
ALTER USER '$WORDPRESS_DB_USER'@'%' IDENTIFIED BY '$WORDPRESS_DB_PASSWORD';
GRANT ALL PRIVILEGES ON wordpress.* TO '$WORDPRESS_DB_USER'@'%';
CREATE USER IF NOT EXISTS '$WORDPRESS_DB_USER2'@'%' IDENTIFIED BY '$WORDPRESS_DB_PASSWORD2';
ALTER USER '$WORDPRESS_DB_USER2'@'%' IDENTIFIED BY '$WORDPRESS_DB_PASSWORD2';
GRANT SELECT, LOCK TABLES, SHOW VIEW ON wordpress.* TO '$WORDPRESS_DB_USER2'@'%';
FLUSH PRIVILEGES;
EOF

exec mariadbd --init-file=/tmp/init.sql
